name: Unit test
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**' #prevent double build on release tag
  pull_request:
    branches:
      - '**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.2.0]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Run unit tests
        run: make test
